// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'es-ES',
  supportedLanguages: ['en-US', 'es-ES'],
  grant_type: 'authorization_code',
  client_id: '5002910318076066',
  client_secret: 'B46Y2ysxmR4aHfmcAnCGOuyrBdtpdOUh',
  redirect_uri: 'https://mercado-app-333415.ey.r.appspot.com',
  mercado_libre_api: 'https://api.mercadolibre.com/',
};
